---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sdafilter

<!-- badges: start -->
<!-- badges: end -->

The goal of sdafilter is to provide an R package for our new paper on arXiv; see the link: https://arxiv.org/abs/2002.11992

## Installation

You can install the released version of sdafilter from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("sdafilter")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("dulilun/sdafilter")
```
## Example 1: one sample t test

This is a basic example which shows you how to solve a simple problem:

```{r example 1}
library(sdafilter)
n = 50
p = 100
dat = matrix(rnorm(n*p), nrow=n)
mu = rep(0, p)
mu[1:as.integer(0.1*p)]=0.5
dat = dat+rep(1, n)%*%t(mu)
alpha = 0.2
out = SDA_M(dat, alpha)
print(out)
```

## Example 2: two sample t test
```{r example 2}
p = 100
n = 30
dat_I = matrix(rnorm(n*p),nrow = n)
mu = rep(0, p)
mu[1:10] = 1.5
dat_I = dat_I = rep(1, n)%*%t(mu)
dat_II = matrix(rnorm(n*p), nrow = n)
out = SDA_2S(dat_I, dat_II, alpha=0.05)
print(out)
```
